version: "3"

services:
  oracle-xe-11g-r2:
    image: sath89/oracle-xe-11g
    container_name: oracle-xe-11g-r2
    restart: always
    ports:
      - "1521:1521"
      - "9090:8080"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./oracle-xe-11g-r2:/u01/app/oracle sath89/oracle-xe-11g